version: "3.9"

services:
  postgres-auth:
    image: postgres:15-alpine
    container_name: postgres-auth
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-enterpriseauth}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-tasks:
    image: postgres:15-alpine
    container_name: postgres-tasks
    restart: always
    ports:
      - "5439:5432"
    volumes:
      - postgres_task_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-enterprisetasks}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:7.1
    container_name: pgadmin4_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres-auth
      - postgres-tasks

  auth_service:
    build:
      context: ./src/auth.service
    container_name: auth-service
    ports:
      - "5006:80"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__DefaultConnection: >
        Host=postgres-auth;
        Port=5432;
        Database=${POSTGRES_DB:-enterpriseauth};
        Username=${POSTGRES_USER:-postgres};
        Password=${POSTGRES_PASSWORD:-postgres};
    depends_on:
      postgres-auth:
        condition: service_healthy

  users_service:
    build:
      context: ./src/users.service
    container_name: users-service
    ports:
      - "5152:80"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__DefaultConnection: >
        Host=postgres-tasks;
        Port=5432;
        Database=${POSTGRES_DB:-enterprisetasks};
        Username=${POSTGRES_USER:-postgres};
        Password=${POSTGRES_PASSWORD:-postgres};
    depends_on:
      postgres-tasks:
        condition: service_healthy

  gateway:
    build:
      context: ./src/gateway
    container_name: gateway
    ports:
      - "5130:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:80
    depends_on:
      - auth_service
      - users_service

volumes:
  postgres_auth_data:
  postgres_task_data:
  pgadmin-data:
