<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.0-rc.2.24473.11" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0-rc.2.24473.11" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\shared\shared.csproj" />  
    <ProjectReference Include="..\auth.shared\auth.shared.csproj"/>
    <ProjectReference Include="..\auth.core\auth.core.csproj"/>
    <ProjectReference Include="..\auth.infrastructure\auth.infrastructure.csproj"/>
  </ItemGroup>
</Project>